name: test_driven
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Service Locator
  get_it: 5.0.1

  # Bloc for State Management
  flutter_bloc: 6.0.6

  # Value equality
  equatable: 1.2.5

  # Functional programming thingies
  dartz: 0.9.2

  # Remote API
  connectivity: 0.4.9+3
  http: 0.12.2

  # Local Cache
  shared_preferences: 0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.2

flutter:
  uses-material-design: true
